name: "Veracode Static Analysis Repository Scan"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "analyze"
  analyze:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Veracode Static Analysis
      - name: Veracode Static Analysis
        uses: veracode/veracode-sca-action@master
        with:
          vid: "${{ secrets.VERACODE_API_ID }}"
          vkey: "${{ secrets.VERACODE_API_KEY }}"
          type: "repository"
          debug: true
          fail_on_severity: "Very High, High"
          # Optional parameters
          # scan_timeout: "15"
          # policy_name: "Your Policy Name"
          # baseline_file: "baseline.json"
