veracode_static_scan:
  push:
    trigger: true
    # Specify either branches_to_run or branches_to_exclude, not both
    branches_to_run:
      - "*"
    branches_to_exclude: []
  pull_request:
    trigger: false
    action:
      - opened
      - synchronize
    target_branch:
      - default_branch
  # If analysis_on_platform is true, Veracode saves the last scan result on the default branch
  analysis_on_platform: false
  # Build will break if findings violate the policy
  break_build_policy_findings: true
  # Build will break if the policy name is invalid
  break_build_invalid_policy: true
  # Build will not break if the scan fails or errors
  break_build_on_error: false
  error_message: "Veracode static scan faced a problem. Please contact your Veracode administrator for more information."
  # Default policy used if no policy is assigned to the application profile
  policy: "Veracode Recommended Medium + SCA"
  # GitHub security code scanning alerts for static findings
  create_code_scanning_alert: false
  # GitHub Issues will not be created for static findings
  create_issue: false
  issues:
    trigger: false
    commands:
      - "Veracode Static Scan"

ruby:
  version: 3.2.2
  bundle: 2.4.6

veracode_static_scan_build:
  runs_on: default
  packager_image: veracode/scm-packaging:3.0.0
  predependency_command: |
    apt-get install -y vim

veracode_sca_scan_build:
  runs_on: default
  packager_image: default
  predependency_command: |
    # Add any predependency commands here
