name: "Veracode Static Analysis Repository Scan"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "analyze"
  analyze:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Veracode Static Analysis
      - name: Veracode Static Analysis
        uses: veracode/veracode-sca-action@master
        with:
          vid: "${{ secrets.VERACODE_API_ID }}"
          vkey: "${{ secrets.VERACODE_API_KEY }}"
          type: "repository"
          debug: true
          fail_on_severity: "Very High, High"
          # Optional parameters
          # scan_timeout: "15"
          # policy_name: "Your Policy Name"
          # baseline_file: "baseline.json"

      # Veracode Static Scan
      - name: Veracode Static Scan
        uses: veracode/veracode-scan-action@master
        with:
          vid: "${{ secrets.VERACODE_API_ID }}"
          vkey: "${{ secrets.VERACODE_API_KEY }}"
          type: "repository"
          debug: true
          fail_on_severity: "Very High, High"
          policy: "Veracode Recommended Medium + SCA"
          break_build_policy_findings: true
          break_build_invalid_policy: true
          break_build_on_error: false
          error_message: "Veracode static scan faced a problem. Please contact your Veracode administrator for more information."
          create_code_scanning_alert: false
          create_issue: false
          issues:
            trigger: false
            commands:
              - "Veracode Static Scan"

      # Veracode SCA Scan
      - name: Veracode SCA Scan
        uses: veracode/veracode-sca-action@master
        with:
          vid: "${{ secrets.VERACODE_API_ID }}"
          vkey: "${{ secrets.VERACODE_API_KEY }}"
          type: "repository"
          debug: true
          fail_on_severity: "Very High, High"
          break_build_on_error: true
          error_message: "Veracode SCA scan faced a problem. Please contact your Veracode administrator for more information."
          issues:
            trigger: false
            commands:
              - "Veracode SCA Scan"

      # Install Ruby and Bundler
      - name: Install Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
          bundler-version: 2.4.6

      # Install SCM Packaging
      - name: Install SCM Packaging
        uses: veracode/scm-packaging@v3.0.0
        with:
          runs_on: ubuntu-latest
          predependency_command: |
            apt-get install -y vim
